name: todoList 自动部署
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 设置 pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      # 设置 Node.js 版本
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 安装依赖
      - run: pnpm install

      # 构建项目
      - run: pnpm run build

      # 部署到 GitHub Pages
      - name: action-Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          BRANCH: gh-pages
          publish_dir: ./dist
